// Define these variables in VSC settings.js and select "local" 
// as "REST Client Environment"
// "rest-client.environmentVariables": {
//
//        "local": {
//           "HOST": "localhost",
//           "PORT": "3001"
//       }
//   }
//-------------------------
// OR COMMENT THESE OUT
//@PORT=3001
//@HOST=localhost
//
//-------------------------
// GET ALL USERS
GET http://{{HOST}}:{{PORT}}/api/users

###
//-------------------------
// GET A USER by name or id (change nickname/id at the end of path)
GET http://{{HOST}}:{{PORT}}/api/users/name/"Mocha Admin"
###
GET http://{{HOST}}:{{PORT}}/api/users/id/5f0411b42f870c4ebc46ba05

###
//
// POST a user, userType enum : ['user','moderator','admin']
// default "user"
POST http://{{HOST}}:{{PORT}}/api/users/
Content-Type: application/json

{
  	"nickname": "Mocha Deplorable",
	"email": "mocha.deplorable@gmail.com",
	"userType": "user", 
	//"nickname": "Mocha Admin",
    //"email": "mocha.admin@gmail.com",
    //"userType": "admin",
	"password": "salasana" 
}

###
// LOGIN

//@authToken = {{login.response.headers.X-AuthToken}} ei toimi, kopsaa käsin login responsesta
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmMWE4OTUwYjIwMWRmNjc0NDI4ODZjYiIsImlhdCI6MTU5NTU3NjE1Mn0.-8xJzsHB1m--gxMSUuA92wT659k3M86z6OkQaAa9XHA

// LOGIN
// returns fullname and token
POST http://{{HOST}}:{{PORT}}/api/users/login
Content-Type: application/json

{
	//Mocha Deplorable
	//"email": "mocha.deplorable@gmail.com",
	//Mocha Admin
	"email": "mocha.admin@gmail.com",
  	"password": "salasana"
	//"email": {"$gt":""}, // this injection does not work
	//"password": {"$gt":""}
}

###


//@authToken = {{login.response.headers.body.$.token}}

//-------------------------
//DELETE http://{{HOST}}:{{PORT}}/api/users/name_or_id
DELETE http://{{HOST}}:{{PORT}}/api/users/5f1a8d20a112503c40b304bc
//Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc2thIEpva3VuZW4iLCJpZCI6IjVlZWI2MjJmMTQ5ZWNiM2E4MGE4MTExNCIsImlhdCI6MTU5MjU1MDg4N30.KIeV5xe8Z9obPWP6CHEyQ9_SlcmeJJuAaWFY4Tlwnr0
Authorization: bearer {{authToken}}
###

PUT http://{{HOST}}:{{PORT}}/api/users/
Content-Type: application/json
Authorization: bearer {{authToken}}

{
	"id": "5f1a8ef33780da1164c2ae07",
	//"email": "mochax@gmail.com"
  	"nickname": "Mocha java"
	//"description": "new cafe -admin",
	//"userType": "admin" 
}